/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestPrivacyPolicyIndexRouteImport } from './routes/_guest/privacy-policy/index'
import { Route as GuestTermsOfServiceIndexRouteImport } from './routes/_guest/terms-of-service/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestPrivacyPolicyIndexRoute = GuestPrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestTermsOfServiceIndexRoute =
  GuestTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => GuestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof GuestIndexRoute
  '/privacy-policy/': typeof GuestPrivacyPolicyIndexRoute
  '/terms-of-service/': typeof GuestTermsOfServiceIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof GuestIndexRoute
  '/privacy-policy': typeof GuestPrivacyPolicyIndexRoute
  '/terms-of-service': typeof GuestTermsOfServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/': typeof GuestIndexRoute
  '/_guest/privacy-policy/': typeof GuestPrivacyPolicyIndexRoute
  '/_guest/terms-of-service/': typeof GuestTermsOfServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/privacy-policy/' | '/terms-of-service/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/privacy-policy' | '/terms-of-service'
  id:
    | '__root__'
    | '/$'
    | '/_guest'
    | '/_guest/'
    | '/_guest/privacy-policy/'
    | '/_guest/terms-of-service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/privacy-policy/': {
      id: '/_guest/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof GuestPrivacyPolicyIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/terms-of-service/': {
      id: '/_guest/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof GuestTermsOfServiceIndexRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface GuestRouteChildren {
  GuestIndexRoute: typeof GuestIndexRoute
  GuestPrivacyPolicyIndexRoute: typeof GuestPrivacyPolicyIndexRoute
  GuestTermsOfServiceIndexRoute: typeof GuestTermsOfServiceIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestIndexRoute: GuestIndexRoute,
  GuestPrivacyPolicyIndexRoute: GuestPrivacyPolicyIndexRoute,
  GuestTermsOfServiceIndexRoute: GuestTermsOfServiceIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
