use crate::utill::types::client::Client;

pub fn get_clients() -> Vec<Client> {
    vec![
        Client {
            id: "client_001".to_string(),
            organization_id: 1,
            name: "Acme Corporation".to_string(),
            email: "contact@acme.com".to_string(),
            phone: "+1-416-555-1001".to_string(),
            address: "100 King St W".to_string(),
            city: "Toronto".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-01T09:00:00Z".to_string(),
        },
        Client {
            id: "client_002".to_string(),
            organization_id: 1,
            name: "Northwind Traders".to_string(),
            email: "hello@northwind.ca".to_string(),
            phone: "+1-416-555-1002".to_string(),
            address: "220 Bay St".to_string(),
            city: "Toronto".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-02T09:00:00Z".to_string(),
        },
        Client {
            id: "client_003".to_string(),
            organization_id: 1,
            name: "Globex Inc.".to_string(),
            email: "info@globex.com".to_string(),
            phone: "+1-416-555-1003".to_string(),
            address: "15 Front St E".to_string(),
            city: "Toronto".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-03T09:00:00Z".to_string(),
        },
        Client {
            id: "client_004".to_string(),
            organization_id: 1,
            name: "Initech".to_string(),
            email: "support@initech.com".to_string(),
            phone: "+1-416-555-1004".to_string(),
            address: "45 Adelaide St".to_string(),
            city: "Toronto".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-04T09:00:00Z".to_string(),
        },
        Client {
            id: "client_005".to_string(),
            organization_id: 1,
            name: "Umbrella Group".to_string(),
            email: "sales@umbrella.com".to_string(),
            phone: "+1-416-555-1005".to_string(),
            address: "88 Queen St".to_string(),
            city: "Toronto".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-05T09:00:00Z".to_string(),
        },
        Client {
            id: "client_006".to_string(),
            organization_id: 1,
            name: "Wayne Enterprises".to_string(),
            email: "contact@wayne.com".to_string(),
            phone: "+1-416-555-1006".to_string(),
            address: "12 Richmond St".to_string(),
            city: "Toronto".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-06T09:00:00Z".to_string(),
        },
        Client {
            id: "client_007".to_string(),
            organization_id: 2,
            name: "Stark Industries".to_string(),
            email: "info@stark.com".to_string(),
            phone: "+1-604-555-1007".to_string(),
            address: "500 Georgia St".to_string(),
            city: "Vancouver".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-07T09:00:00Z".to_string(),
        },
        Client {
            id: "client_008".to_string(),
            organization_id: 2,
            name: "Wonka Foods".to_string(),
            email: "hello@wonka.com".to_string(),
            phone: "+1-604-555-1008".to_string(),
            address: "101 Granville St".to_string(),
            city: "Vancouver".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-08T09:00:00Z".to_string(),
        },
        Client {
            id: "client_009".to_string(),
            organization_id: 2,
            name: "Hooli".to_string(),
            email: "admin@hooli.com".to_string(),
            phone: "+1-604-555-1009".to_string(),
            address: "88 Robson St".to_string(),
            city: "Vancouver".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-09T09:00:00Z".to_string(),
        },
        Client {
            id: "client_010".to_string(),
            organization_id: 2,
            name: "Pied Piper".to_string(),
            email: "team@piedpiper.io".to_string(),
            phone: "+1-604-555-1010".to_string(),
            address: "700 Burrard St".to_string(),
            city: "Vancouver".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-10T09:00:00Z".to_string(),
        },
        Client {
            id: "client_011".to_string(),
            organization_id: 3,
            name: "Soylent Corp".to_string(),
            email: "info@soylent.com".to_string(),
            phone: "+1-514-555-1011".to_string(),
            address: "50 Rue Sainte-Catherine".to_string(),
            city: "Montreal".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-11T09:00:00Z".to_string(),
        },
        Client {
            id: "client_012".to_string(),
            organization_id: 3,
            name: "Cyberdyne Systems".to_string(),
            email: "contact@cyberdyne.com".to_string(),
            phone: "+1-514-555-1012".to_string(),
            address: "99 Sherbrooke St".to_string(),
            city: "Montreal".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-12T09:00:00Z".to_string(),
        },
        Client {
            id: "client_013".to_string(),
            organization_id: 3,
            name: "Oscorp".to_string(),
            email: "hello@oscorp.com".to_string(),
            phone: "+1-514-555-1013".to_string(),
            address: "18 Peel St".to_string(),
            city: "Montreal".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-13T09:00:00Z".to_string(),
        },
        Client {
            id: "client_014".to_string(),
            organization_id: 3,
            name: "Tyrell Corporation".to_string(),
            email: "support@tyrell.com".to_string(),
            phone: "+1-514-555-1014".to_string(),
            address: "500 René-Lévesque Blvd".to_string(),
            city: "Montreal".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-14T09:00:00Z".to_string(),
        },
        Client {
            id: "client_015".to_string(),
            organization_id: 4,
            name: "Black Mesa".to_string(),
            email: "admin@blackmesa.com".to_string(),
            phone: "+1-403-555-1015".to_string(),
            address: "80 8 Ave SW".to_string(),
            city: "Calgary".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-15T09:00:00Z".to_string(),
        },
        Client {
            id: "client_016".to_string(),
            organization_id: 4,
            name: "Aperture Science".to_string(),
            email: "lab@aperture.com".to_string(),
            phone: "+1-403-555-1016".to_string(),
            address: "25 Stephen Ave".to_string(),
            city: "Calgary".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-16T09:00:00Z".to_string(),
        },
        Client {
            id: "client_017".to_string(),
            organization_id: 4,
            name: "LexCorp".to_string(),
            email: "sales@lexcorp.com".to_string(),
            phone: "+1-403-555-1017".to_string(),
            address: "120 Centre St".to_string(),
            city: "Calgary".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-17T09:00:00Z".to_string(),
        },
        Client {
            id: "client_018".to_string(),
            organization_id: 4,
            name: "Massive Dynamic".to_string(),
            email: "info@massivedynamic.com".to_string(),
            phone: "+1-403-555-1018".to_string(),
            address: "10 4 Ave SW".to_string(),
            city: "Calgary".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-18T09:00:00Z".to_string(),
        },
        Client {
            id: "client_019".to_string(),
            organization_id: 5,
            name: "Vehement Capital".to_string(),
            email: "contact@vehement.com".to_string(),
            phone: "+1-613-555-1019".to_string(),
            address: "90 Wellington St".to_string(),
            city: "Ottawa".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-19T09:00:00Z".to_string(),
        },
        Client {
            id: "client_020".to_string(),
            organization_id: 5,
            name: "Blue Yonder".to_string(),
            email: "hello@blueyonder.com".to_string(),
            phone: "+1-613-555-1020".to_string(),
            address: "55 Elgin St".to_string(),
            city: "Ottawa".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-20T09:00:00Z".to_string(),
        },
        Client {
            id: "client_021".to_string(),
            organization_id: 5,
            name: "Quantum Labs".to_string(),
            email: "info@quantumlabs.com".to_string(),
            phone: "+1-613-555-1021".to_string(),
            address: "120 Bank St".to_string(),
            city: "Ottawa".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-21T09:00:00Z".to_string(),
        },
        Client {
            id: "client_022".to_string(),
            organization_id: 5,
            name: "Fusion Tech".to_string(),
            email: "support@fusiontech.com".to_string(),
            phone: "+1-613-555-1022".to_string(),
            address: "200 Rideau St".to_string(),
            city: "Ottawa".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-22T09:00:00Z".to_string(),
        },
        Client {
            id: "client_023".to_string(),
            organization_id: 6,
            name: "Evergreen Solutions".to_string(),
            email: "contact@evergreen.com".to_string(),
            phone: "+1-902-555-1023".to_string(),
            address: "75 Spring Garden Rd".to_string(),
            city: "Halifax".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-23T09:00:00Z".to_string(),
        },
        Client {
            id: "client_024".to_string(),
            organization_id: 6,
            name: "Maple Innovations".to_string(),
            email: "info@mapleinnovations.ca".to_string(),
            phone: "+1-902-555-1024".to_string(),
            address: "30 Barrington St".to_string(),
            city: "Halifax".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-24T09:00:00Z".to_string(),
        },
        Client {
            id: "client_025".to_string(),
            organization_id: 6,
            name: "Nova Systems".to_string(),
            email: "hello@novasystems.ca".to_string(),
            phone: "+1-902-555-1025".to_string(),
            address: "200 Hollis St".to_string(),
            city: "Halifax".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-25T09:00:00Z".to_string(),
        },
        Client {
            id: "client_026".to_string(),
            organization_id: 6,
            name: "Prairie Software".to_string(),
            email: "sales@prairiesoftware.ca".to_string(),
            phone: "+1-306-555-1026".to_string(),
            address: "100 2nd Ave".to_string(),
            city: "Saskatoon".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-26T09:00:00Z".to_string(),
        },
        Client {
            id: "client_027".to_string(),
            organization_id: 7,
            name: "Northern Logistics".to_string(),
            email: "info@northernlogistics.ca".to_string(),
            phone: "+1-204-555-1027".to_string(),
            address: "400 Main St".to_string(),
            city: "Winnipeg".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-27T09:00:00Z".to_string(),
        },
        Client {
            id: "client_028".to_string(),
            organization_id: 7,
            name: "Polar Energy".to_string(),
            email: "contact@polarenergy.ca".to_string(),
            phone: "+1-204-555-1028".to_string(),
            address: "50 Portage Ave".to_string(),
            city: "Winnipeg".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-28T09:00:00Z".to_string(),
        },
        Client {
            id: "client_029".to_string(),
            organization_id: 7,
            name: "Redwood Consulting".to_string(),
            email: "hello@redwoodconsulting.ca".to_string(),
            phone: "+1-204-555-1029".to_string(),
            address: "300 Graham Ave".to_string(),
            city: "Winnipeg".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-29T09:00:00Z".to_string(),
        },
        Client {
            id: "client_030".to_string(),
            organization_id: 7,
            name: "Aurora Digital".to_string(),
            email: "team@auroradigital.ca".to_string(),
            phone: "+1-204-555-1030".to_string(),
            address: "15 Broadway".to_string(),
            city: "Winnipeg".to_string(),
            country: "Canada".to_string(),
            created_at: "2026-01-30T09:00:00Z".to_string(),
        },
    ]
}
