use crate::utill::types::dashboard::{
    Dashboard, DashboardStats, InvoiceStatusCount, MonthlyRevenue,
};

pub fn get_dashboard_data() -> Dashboard {
    Dashboard {
        dashboard_stats: DashboardStats {
            total_revenue: 125_000.00,
            paid_count: 48,
            pending_count: 12,
            overdue_count: 5,
            currency: "USD",
        },
        invoices_status: vec![
            InvoiceStatusCount {
                id: "some-id-01",
                status: "Paid",
                count: 48,
            },
            InvoiceStatusCount {
                id: "some-id-02",
                status: "Sent",
                count: 25,
            },
            InvoiceStatusCount {
                id: "some-id-03",
                status: "Draft",
                count: 15,
            },
            InvoiceStatusCount {
                id: "some-id-04",
                status: "Overdue",
                count: 5,
            },
        ],
        monthly_revenue: vec![
            // 2026 Data
            MonthlyRevenue {
                month: "Jan",
                year: 2026,
                currency: "USD",
                amount: 12000,
            },
            MonthlyRevenue {
                month: "Jan",
                year: 2026,
                currency: "EUR",
                amount: 8500,
            },
            MonthlyRevenue {
                month: "Jan",
                year: 2026,
                currency: "GBP",
                amount: 6200,
            },
            MonthlyRevenue {
                month: "Jan",
                year: 2026,
                currency: "NGN",
                amount: 150000,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2026,
                currency: "USD",
                amount: 15000,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2026,
                currency: "EUR",
                amount: 9200,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2026,
                currency: "GBP",
                amount: 7100,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2026,
                currency: "NGN",
                amount: 175000,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2026,
                currency: "USD",
                amount: 18000,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2026,
                currency: "EUR",
                amount: 11000,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2026,
                currency: "GBP",
                amount: 8000,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2026,
                currency: "NGN",
                amount: 200000,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2026,
                currency: "USD",
                amount: 22000,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2026,
                currency: "EUR",
                amount: 13500,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2026,
                currency: "GBP",
                amount: 9500,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2026,
                currency: "NGN",
                amount: 225000,
            },
            MonthlyRevenue {
                month: "May",
                year: 2026,
                currency: "USD",
                amount: 19500,
            },
            MonthlyRevenue {
                month: "May",
                year: 2026,
                currency: "EUR",
                amount: 12000,
            },
            MonthlyRevenue {
                month: "May",
                year: 2026,
                currency: "GBP",
                amount: 8700,
            },
            MonthlyRevenue {
                month: "May",
                year: 2026,
                currency: "NGN",
                amount: 210000,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2026,
                currency: "USD",
                amount: 25000,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2026,
                currency: "EUR",
                amount: 15500,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2026,
                currency: "GBP",
                amount: 11000,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2026,
                currency: "NGN",
                amount: 250000,
            },
            // 2025 Data
            MonthlyRevenue {
                month: "Jan",
                year: 2025,
                currency: "USD",
                amount: 10000,
            },
            MonthlyRevenue {
                month: "Jan",
                year: 2025,
                currency: "EUR",
                amount: 7200,
            },
            MonthlyRevenue {
                month: "Jan",
                year: 2025,
                currency: "GBP",
                amount: 5400,
            },
            MonthlyRevenue {
                month: "Jan",
                year: 2025,
                currency: "NGN",
                amount: 130000,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2025,
                currency: "USD",
                amount: 11500,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2025,
                currency: "EUR",
                amount: 8000,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2025,
                currency: "GBP",
                amount: 6000,
            },
            MonthlyRevenue {
                month: "Feb",
                year: 2025,
                currency: "NGN",
                amount: 145000,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2025,
                currency: "USD",
                amount: 13000,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2025,
                currency: "EUR",
                amount: 8800,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2025,
                currency: "GBP",
                amount: 6700,
            },
            MonthlyRevenue {
                month: "Mar",
                year: 2025,
                currency: "NGN",
                amount: 160000,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2025,
                currency: "USD",
                amount: 14500,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2025,
                currency: "EUR",
                amount: 9500,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2025,
                currency: "GBP",
                amount: 7200,
            },
            MonthlyRevenue {
                month: "Apr",
                year: 2025,
                currency: "NGN",
                amount: 175000,
            },
            MonthlyRevenue {
                month: "May",
                year: 2025,
                currency: "USD",
                amount: 16000,
            },
            MonthlyRevenue {
                month: "May",
                year: 2025,
                currency: "EUR",
                amount: 10200,
            },
            MonthlyRevenue {
                month: "May",
                year: 2025,
                currency: "GBP",
                amount: 7800,
            },
            MonthlyRevenue {
                month: "May",
                year: 2025,
                currency: "NGN",
                amount: 190000,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2025,
                currency: "USD",
                amount: 17500,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2025,
                currency: "EUR",
                amount: 11000,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2025,
                currency: "GBP",
                amount: 8300,
            },
            MonthlyRevenue {
                month: "Jun",
                year: 2025,
                currency: "NGN",
                amount: 200000,
            },
        ],
    }
}
