use crate::utill::types::invoice::{Invoice, InvoiceItem, InvoiceStatus};

pub fn get_invoices() -> Vec<Invoice> {
    vec![
        Invoice {
            id: "inv_0001".to_string(),
            invoice_number: "INV-2026-0001".to_string(),
            client_id: "client_001".to_string(),
            items: vec![InvoiceItem {
                description: "Website Design".to_string(),
                quantity: 1,
                price: 1200.0,
            }],
            tax_rate: 0.13,
            discount: 50.0,
            status: InvoiceStatus::Paid,
            signature: Some("John Doe".to_string()),
            issue_date: "2026-01-02".to_string(),
            due_date: "2026-02-01".to_string(),
            currency: "CAD".to_string(),
            notes: "Paid via bank transfer.".to_string(),
            created_at: "2026-01-02T09:00:00Z".to_string(),
        },
        Invoice {
            id: "inv_0002".to_string(),
            invoice_number: "INV-2026-0002".to_string(),
            client_id: "client_002".to_string(),
            items: vec![InvoiceItem {
                description: "SEO Services".to_string(),
                quantity: 2,
                price: 450.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-01-05".to_string(),
            due_date: "2026-02-04".to_string(),
            currency: "CAD".to_string(),
            notes: "".to_string(),
            created_at: "2026-01-05T11:20:00Z".to_string(),
        },
        Invoice {
            id: "inv_0003".to_string(),
            invoice_number: "INV-2026-0003".to_string(),
            client_id: "client_003".to_string(),
            items: vec![InvoiceItem {
                description: "Mobile App Development".to_string(),
                quantity: 1,
                price: 8500.0,
            }],
            tax_rate: 0.13,
            discount: 500.0,
            status: InvoiceStatus::Draft,
            signature: None,
            issue_date: "2026-01-07".to_string(),
            due_date: "2026-02-06".to_string(),
            currency: "CAD".to_string(),
            notes: "Awaiting approval.".to_string(),
            created_at: "2026-01-07T14:00:00Z".to_string(),
        },
        Invoice {
            id: "inv_0004".to_string(),
            invoice_number: "INV-2026-0004".to_string(),
            client_id: "client_004".to_string(),
            items: vec![InvoiceItem {
                description: "Cloud Hosting".to_string(),
                quantity: 12,
                price: 80.0,
            }],
            tax_rate: 0.13,
            discount: 100.0,
            status: InvoiceStatus::Overdue,
            signature: Some("Jane Smith".to_string()),
            issue_date: "2026-01-10".to_string(),
            due_date: "2026-02-09".to_string(),
            currency: "CAD".to_string(),
            notes: "Reminder sent.".to_string(),
            created_at: "2026-01-10T08:30:00Z".to_string(),
        },
        Invoice {
            id: "inv_0005".to_string(),
            invoice_number: "INV-2026-0005".to_string(),
            client_id: "client_005".to_string(),
            items: vec![InvoiceItem {
                description: "IT Consulting".to_string(),
                quantity: 10,
                price: 150.0,
            }],
            tax_rate: 0.13,
            discount: 75.0,
            status: InvoiceStatus::Paid,
            signature: Some("Michael Lee".to_string()),
            issue_date: "2026-01-12".to_string(),
            due_date: "2026-02-11".to_string(),
            currency: "CAD".to_string(),
            notes: "".to_string(),
            created_at: "2026-01-12T10:15:00Z".to_string(),
        },
        // 6
        Invoice {
            id: "inv_0006".into(),
            invoice_number: "INV-2026-0006".into(),
            client_id: "client_006".into(),
            items: vec![InvoiceItem {
                description: "Logo Design".into(),
                quantity: 1,
                price: 600.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-01-15".into(),
            due_date: "2026-02-14".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-01-15T09:30:00Z".into(),
        },
        // 7
        Invoice {
            id: "inv_0007".into(),
            invoice_number: "INV-2026-0007".into(),
            client_id: "client_007".into(),
            items: vec![InvoiceItem {
                description: "API Integration".into(),
                quantity: 20,
                price: 120.0,
            }],
            tax_rate: 0.13,
            discount: 200.0,
            status: InvoiceStatus::Paid,
            signature: Some("Sarah Brown".into()),
            issue_date: "2026-01-18".into(),
            due_date: "2026-02-17".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-01-18T13:00:00Z".into(),
        },
        // 8
        Invoice {
            id: "inv_0008".into(),
            invoice_number: "INV-2026-0008".into(),
            client_id: "client_008".into(),
            items: vec![InvoiceItem {
                description: "Database Migration".into(),
                quantity: 1,
                price: 2400.0,
            }],
            tax_rate: 0.13,
            discount: 100.0,
            status: InvoiceStatus::Draft,
            signature: None,
            issue_date: "2026-01-20".into(),
            due_date: "2026-02-19".into(),
            currency: "CAD".into(),
            notes: "Pending client review.".into(),
            created_at: "2026-01-20T15:45:00Z".into(),
        },
        // 9
        Invoice {
            id: "inv_0009".into(),
            invoice_number: "INV-2026-0009".into(),
            client_id: "client_009".into(),
            items: vec![InvoiceItem {
                description: "Content Writing".into(),
                quantity: 25,
                price: 45.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Paid,
            signature: Some("Emily Davis".into()),
            issue_date: "2026-01-22".into(),
            due_date: "2026-02-21".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-01-22T12:10:00Z".into(),
        },
        // 10
        Invoice {
            id: "inv_0010".into(),
            invoice_number: "INV-2026-0010".into(),
            client_id: "client_010".into(),
            items: vec![InvoiceItem {
                description: "Marketing Campaign".into(),
                quantity: 1,
                price: 3500.0,
            }],
            tax_rate: 0.13,
            discount: 250.0,
            status: InvoiceStatus::Overdue,
            signature: None,
            issue_date: "2026-01-25".into(),
            due_date: "2026-02-24".into(),
            currency: "CAD".into(),
            notes: "Second reminder issued.".into(),
            created_at: "2026-01-25T10:00:00Z".into(),
        },
        // 11-30 follow the same pattern with unique values...
        Invoice {
            id: "inv_0011".into(),
            invoice_number: "INV-2026-0011".into(),
            client_id: "client_011".into(),
            items: vec![InvoiceItem {
                description: "Security Audit".into(),
                quantity: 1,
                price: 1800.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-02-01".into(),
            due_date: "2026-03-03".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-01T09:00:00Z".into(),
        },
        Invoice {
            id: "inv_0012".into(),
            invoice_number: "INV-2026-0012".into(),
            client_id: "client_012".into(),
            items: vec![InvoiceItem {
                description: "UX Research".into(),
                quantity: 15,
                price: 95.0,
            }],
            tax_rate: 0.13,
            discount: 100.0,
            status: InvoiceStatus::Paid,
            signature: Some("Alice".into()),
            issue_date: "2026-02-03".into(),
            due_date: "2026-03-05".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-03T08:45:00Z".into(),
        },
        Invoice {
            id: "inv_0013".into(),
            invoice_number: "INV-2026-0013".into(),
            client_id: "client_013".into(),
            items: vec![InvoiceItem {
                description: "Video Editing".into(),
                quantity: 8,
                price: 110.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Draft,
            signature: None,
            issue_date: "2026-02-05".into(),
            due_date: "2026-03-07".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-05T13:00:00Z".into(),
        },
        Invoice {
            id: "inv_0014".into(),
            invoice_number: "INV-2026-0014".into(),
            client_id: "client_014".into(),
            items: vec![InvoiceItem {
                description: "Graphic Design".into(),
                quantity: 12,
                price: 70.0,
            }],
            tax_rate: 0.13,
            discount: 20.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-02-08".into(),
            due_date: "2026-03-10".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-08T09:20:00Z".into(),
        },
        Invoice {
            id: "inv_0015".into(),
            invoice_number: "INV-2026-0015".into(),
            client_id: "client_015".into(),
            items: vec![InvoiceItem {
                description: "Software License".into(),
                quantity: 30,
                price: 40.0,
            }],
            tax_rate: 0.13,
            discount: 150.0,
            status: InvoiceStatus::Paid,
            signature: Some("Robert".into()),
            issue_date: "2026-02-10".into(),
            due_date: "2026-03-12".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-10T16:30:00Z".into(),
        },
        // Continue similarly...
        Invoice {
            id: "inv_0016".into(),
            invoice_number: "INV-2026-0016".into(),
            client_id: "client_016".into(),
            items: vec![InvoiceItem {
                description: "Maintenance".into(),
                quantity: 6,
                price: 200.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-02-12".into(),
            due_date: "2026-03-14".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-12T11:00:00Z".into(),
        },
        Invoice {
            id: "inv_0017".into(),
            invoice_number: "INV-2026-0017".into(),
            client_id: "client_017".into(),
            items: vec![InvoiceItem {
                description: "Training".into(),
                quantity: 2,
                price: 900.0,
            }],
            tax_rate: 0.13,
            discount: 50.0,
            status: InvoiceStatus::Paid,
            signature: Some("David".into()),
            issue_date: "2026-02-15".into(),
            due_date: "2026-03-17".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-15T09:00:00Z".into(),
        },
        Invoice {
            id: "inv_0018".into(),
            invoice_number: "INV-2026-0018".into(),
            client_id: "client_018".into(),
            items: vec![InvoiceItem {
                description: "AI Consultation".into(),
                quantity: 5,
                price: 500.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Draft,
            signature: None,
            issue_date: "2026-02-18".into(),
            due_date: "2026-03-20".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-18T10:30:00Z".into(),
        },
        Invoice {
            id: "inv_0019".into(),
            invoice_number: "INV-2026-0019".into(),
            client_id: "client_019".into(),
            items: vec![InvoiceItem {
                description: "Server Setup".into(),
                quantity: 3,
                price: 750.0,
            }],
            tax_rate: 0.13,
            discount: 100.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-02-20".into(),
            due_date: "2026-03-22".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-20T14:15:00Z".into(),
        },
        Invoice {
            id: "inv_0020".into(),
            invoice_number: "INV-2026-0020".into(),
            client_id: "client_020".into(),
            items: vec![InvoiceItem {
                description: "Email Hosting".into(),
                quantity: 24,
                price: 12.5,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Overdue,
            signature: None,
            issue_date: "2026-02-23".into(),
            due_date: "2026-03-25".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-23T08:00:00Z".into(),
        },
        Invoice {
            id: "inv_0021".into(),
            invoice_number: "INV-2026-0021".into(),
            client_id: "client_021".into(),
            items: vec![InvoiceItem {
                description: "Data Analytics".into(),
                quantity: 12,
                price: 130.0,
            }],
            tax_rate: 0.13,
            discount: 120.0,
            status: InvoiceStatus::Paid,
            signature: Some("Chris".into()),
            issue_date: "2026-02-25".into(),
            due_date: "2026-03-27".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-25T15:30:00Z".into(),
        },
        Invoice {
            id: "inv_0022".into(),
            invoice_number: "INV-2026-0022".into(),
            client_id: "client_022".into(),
            items: vec![InvoiceItem {
                description: "DevOps Support".into(),
                quantity: 18,
                price: 95.0,
            }],
            tax_rate: 0.13,
            discount: 80.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-02-27".into(),
            due_date: "2026-03-29".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-02-27T09:40:00Z".into(),
        },
        Invoice {
            id: "inv_0023".into(),
            invoice_number: "INV-2026-0023".into(),
            client_id: "client_023".into(),
            items: vec![InvoiceItem {
                description: "Photography".into(),
                quantity: 1,
                price: 950.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Draft,
            signature: None,
            issue_date: "2026-03-01".into(),
            due_date: "2026-03-31".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-01T12:00:00Z".into(),
        },
        Invoice {
            id: "inv_0024".into(),
            invoice_number: "INV-2026-0024".into(),
            client_id: "client_024".into(),
            items: vec![InvoiceItem {
                description: "Copywriting".into(),
                quantity: 40,
                price: 30.0,
            }],
            tax_rate: 0.13,
            discount: 60.0,
            status: InvoiceStatus::Paid,
            signature: Some("Emma".into()),
            issue_date: "2026-03-03".into(),
            due_date: "2026-04-02".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-03T09:10:00Z".into(),
        },
        Invoice {
            id: "inv_0025".into(),
            invoice_number: "INV-2026-0025".into(),
            client_id: "client_025".into(),
            items: vec![InvoiceItem {
                description: "Brand Strategy".into(),
                quantity: 1,
                price: 4200.0,
            }],
            tax_rate: 0.13,
            discount: 300.0,
            status: InvoiceStatus::Overdue,
            signature: None,
            issue_date: "2026-03-05".into(),
            due_date: "2026-04-04".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-05T08:50:00Z".into(),
        },
        Invoice {
            id: "inv_0026".into(),
            invoice_number: "INV-2026-0026".into(),
            client_id: "client_026".into(),
            items: vec![InvoiceItem {
                description: "Network Monitoring".into(),
                quantity: 6,
                price: 250.0,
            }],
            tax_rate: 0.13,
            discount: 0.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-03-07".into(),
            due_date: "2026-04-06".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-07T11:15:00Z".into(),
        },
        Invoice {
            id: "inv_0027".into(),
            invoice_number: "INV-2026-0027".into(),
            client_id: "client_027".into(),
            items: vec![InvoiceItem {
                description: "CRM Integration".into(),
                quantity: 2,
                price: 1400.0,
            }],
            tax_rate: 0.13,
            discount: 75.0,
            status: InvoiceStatus::Paid,
            signature: Some("Daniel".into()),
            issue_date: "2026-03-10".into(),
            due_date: "2026-04-09".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-10T10:00:00Z".into(),
        },
        Invoice {
            id: "inv_0028".into(),
            invoice_number: "INV-2026-0028".into(),
            client_id: "client_028".into(),
            items: vec![InvoiceItem {
                description: "UI Development".into(),
                quantity: 60,
                price: 55.0,
            }],
            tax_rate: 0.13,
            discount: 250.0,
            status: InvoiceStatus::Draft,
            signature: None,
            issue_date: "2026-03-12".into(),
            due_date: "2026-04-11".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-12T14:00:00Z".into(),
        },
        Invoice {
            id: "inv_0029".into(),
            invoice_number: "INV-2026-0029".into(),
            client_id: "client_029".into(),
            items: vec![InvoiceItem {
                description: "QA Testing".into(),
                quantity: 40,
                price: 45.0,
            }],
            tax_rate: 0.13,
            discount: 90.0,
            status: InvoiceStatus::Pending,
            signature: None,
            issue_date: "2026-03-15".into(),
            due_date: "2026-04-14".into(),
            currency: "CAD".into(),
            notes: "".into(),
            created_at: "2026-03-15T13:10:00Z".into(),
        },
        Invoice {
            id: "inv_0030".into(),
            invoice_number: "INV-2026-0030".into(),
            client_id: "client_030".into(),
            items: vec![InvoiceItem {
                description: "Annual Support Contract".into(),
                quantity: 1,
                price: 5000.0,
            }],
            tax_rate: 0.13,
            discount: 500.0,
            status: InvoiceStatus::Paid,
            signature: Some("Sophia".into()),
            issue_date: "2026-03-18".into(),
            due_date: "2026-04-17".into(),
            currency: "CAD".into(),
            notes: "Thank you for your continued business.".into(),
            created_at: "2026-03-18T09:30:00Z".into(),
        },
    ]
}
