import { Country } from "@/lib/types";

export const COUNTRIES: Country[] = [
    { name: "Afghanistan", currency: "AFN" },
    { name: "Albania", currency: "ALL" },
    { name: "Algeria", currency: "DZD" },
    { name: "Angola", currency: "AOA" },
    { name: "Anguilla", currency: "XCD" },
    { name: "Antigua and Barbuda", currency: "XCD" },
    { name: "Argentina", currency: "ARS" },
    { name: "Armenia", currency: "AMD" },
    { name: "Australia", currency: "AUD" },
    { name: "Austria", currency: "EUR" },
    { name: "Azerbaijan", currency: "AZN" },
    { name: "Bahamas", currency: "BSD" },
    { name: "Bahrain", currency: "BHD" },
    { name: "Bangladesh", currency: "BDT" },
    { name: "Barbados", currency: "BBD" },
    { name: "Belarus", currency: "BYN" },
    { name: "Belgium", currency: "EUR" },
    { name: "Belize", currency: "BZD" },
    { name: "Benin", currency: "XOF" },
    { name: "Bermuda", currency: "BMD" },
    { name: "Bhutan", currency: "BTN" },
    { name: "Bolivia", currency: "BOB" },
    { name: "Bosnia and Herzegovina", currency: "BAM" },
    { name: "Botswana", currency: "BWP" },
    { name: "Brazil", currency: "BRL" },
    { name: "Brunei", currency: "BND" },
    { name: "Bulgaria", currency: "BGN" },
    { name: "Burkina Faso", currency: "XOF" },
    { name: "Cabo Verde", currency: "CVE" },
    { name: "Cambodia", currency: "KHR" },
    { name: "Cameroon", currency: "XAF" },
    { name: "Canada", currency: "CAD" },
    { name: "Cayman Islands", currency: "KYD" },
    { name: "Chad", currency: "XAF" },
    { name: "Chile", currency: "CLP" },
    { name: "China", currency: "CNY" },
    { name: "Colombia", currency: "COP" },
    { name: "Congo", currency: "XAF" },
    { name: "Costa Rica", currency: "CRC" },
    { name: "Côte d'Ivoire", currency: "XOF" },
    { name: "Croatia", currency: "EUR" },
    { name: "Cyprus", currency: "EUR" },
    { name: "Czechia", currency: "CZK" },
    { name: "Democratic Republic of the Congo", currency: "CDF" },
    { name: "Denmark", currency: "DKK" },
    { name: "Dominica", currency: "XCD" },
    { name: "Dominican Republic", currency: "DOP" },
    { name: "Ecuador", currency: "USD" },
    { name: "Egypt", currency: "EGP" },
    { name: "El Salvador", currency: "USD" },
    { name: "Estonia", currency: "EUR" },
    { name: "Eswatini", currency: "SZL" },
    { name: "Fiji", currency: "FJD" },
    { name: "Finland", currency: "EUR" },
    { name: "France", currency: "EUR" },
    { name: "Gabon", currency: "XAF" },
    { name: "Gambia", currency: "GMD" },
    { name: "Georgia", currency: "GEL" },
    { name: "Germany", currency: "EUR" },
    { name: "Ghana", currency: "GHS" },
    { name: "Greece", currency: "EUR" },
    { name: "Grenada", currency: "XCD" },
    { name: "Guatemala", currency: "GTQ" },
    { name: "Guinea-Bissau", currency: "XOF" },
    { name: "Guyana", currency: "GYD" },
    { name: "Honduras", currency: "HNL" },
    { name: "Hong Kong", currency: "HKD" },
    { name: "Hungary", currency: "HUF" },
    { name: "Iceland", currency: "ISK" },
    { name: "India", currency: "INR" },
    { name: "Indonesia", currency: "IDR" },
    { name: "Iraq", currency: "IQD" },
    { name: "Ireland", currency: "EUR" },
    { name: "Israel", currency: "ILS" },
    { name: "Italy", currency: "EUR" },
    { name: "Jamaica", currency: "JMD" },
    { name: "Japan", currency: "JPY" },
    { name: "Jordan", currency: "JOD" },
    { name: "Kazakhstan", currency: "KZT" },
    { name: "Kenya", currency: "KES" },
    { name: "Kosovo", currency: "EUR" },
    { name: "Kuwait", currency: "KWD" },
    { name: "Kyrgyzstan", currency: "KGS" },
    { name: "Laos", currency: "LAK" },
    { name: "Latvia", currency: "EUR" },
    { name: "Lebanon", currency: "LBP" },
    { name: "Liberia", currency: "LRD" },
    { name: "Libya", currency: "LYD" },
    { name: "Liechtenstein", currency: "CHF" },
    { name: "Lithuania", currency: "EUR" },
    { name: "Luxembourg", currency: "EUR" },
    { name: "Macau", currency: "MOP" },
    { name: "Madagascar", currency: "MGA" },
    { name: "Malawi", currency: "MWK" },
    { name: "Malaysia", currency: "MYR" },
    { name: "Maldives", currency: "MVR" },
    { name: "Mali", currency: "XOF" },
    { name: "Malta", currency: "EUR" },
    { name: "Mauritania", currency: "MRU" },
    { name: "Mauritius", currency: "MUR" },
    { name: "Mexico", currency: "MXN" },
    { name: "Moldova", currency: "MDL" },
    { name: "Mongolia", currency: "MNT" },
    { name: "Montenegro", currency: "EUR" },
    { name: "Montserrat", currency: "XCD" },
    { name: "Morocco", currency: "MAD" },
    { name: "Mozambique", currency: "MZN" },
    { name: "Myanmar", currency: "MMK" },
    { name: "Namibia", currency: "NAD" },
    { name: "Nauru", currency: "AUD" },
    { name: "Nepal", currency: "NPR" },
    { name: "Netherlands", currency: "EUR" },
    { name: "New Zealand", currency: "NZD" },
    { name: "Nicaragua", currency: "NIO" },
    { name: "Niger", currency: "XOF" },
    { name: "Nigeria", currency: "NGN" },
    { name: "North Macedonia", currency: "MKD" },
    { name: "Norway", currency: "NOK" },
    { name: "Oman", currency: "OMR" },
    { name: "Pakistan", currency: "PKR" },
    { name: "Panama", currency: "PAB" },
    { name: "Papua New Guinea", currency: "PGK" },
    { name: "Paraguay", currency: "PYG" },
    { name: "Peru", currency: "PEN" },
    { name: "Philippines", currency: "PHP" },
    { name: "Poland", currency: "PLN" },
    { name: "Portugal", currency: "EUR" },
    { name: "Qatar", currency: "QAR" },
    { name: "Romania", currency: "RON" },
    { name: "Rwanda", currency: "RWF" },
    { name: "Saint Kitts and Nevis", currency: "XCD" },
    { name: "Saint Lucia", currency: "XCD" },
    { name: "Saint Vincent and the Grenadines", currency: "XCD" },
    { name: "Saudi Arabia", currency: "SAR" },
    { name: "Senegal", currency: "XOF" },
    { name: "Serbia", currency: "RSD" },
    { name: "Seychelles", currency: "SCR" },
    { name: "Sierra Leone", currency: "SLE" },
    { name: "Singapore", currency: "SGD" },
    { name: "Slovakia", currency: "EUR" },
    { name: "Slovenia", currency: "EUR" },
    { name: "Solomon Islands", currency: "SBD" },
    { name: "South Africa", currency: "ZAR" },
    { name: "South Korea", currency: "KRW" },
    { name: "Spain", currency: "EUR" },
    { name: "Sri Lanka", currency: "LKR" },
    { name: "Suriname", currency: "SRD" },
    { name: "Sweden", currency: "SEK" },
    { name: "Switzerland", currency: "CHF" },
    { name: "Taiwan", currency: "TWD" },
    { name: "Tajikistan", currency: "TJS" },
    { name: "Tanzania", currency: "TZS" },
    { name: "Thailand", currency: "THB" },
    { name: "Tonga", currency: "TOP" },
    { name: "Trinidad and Tobago", currency: "TTD" },
    { name: "Tunisia", currency: "TND" },
    { name: "Türkiye", currency: "TRY" },
    { name: "Turks and Caicos Islands", currency: "USD" },
    { name: "Uganda", currency: "UGX" },
    { name: "Ukraine", currency: "UAH" },
    { name: "United Arab Emirates", currency: "AED" },
    { name: "United Kingdom", currency: "GBP" },
    { name: "United States", currency: "USD" },
    { name: "Uruguay", currency: "UYU" },
    { name: "Uzbekistan", currency: "UZS" },
    { name: "Vanuatu", currency: "VUV" },
    { name: "Venezuela", currency: "VES" },
    { name: "Vietnam", currency: "VND" },
    { name: "Zambia", currency: "ZMW" },
    { name: "Zimbabwe", currency: "ZWG" },
];
